name: "PCA9685 PWM Controller"
version: "0.1.36"
slug: "pca9685_pwm"

description: " PCA9685 controller via MQTT Discovery (PWM, heaters, fans, stepper control)"
init: false
arch:
  - aarch64
  - armv7
  - armhf
  - amd64
startup: "services"
boot: auto
host_network: true
homeassistant_api: true
map:
  - config
  - dev
kernel_modules:
  - i2c-dev
privileged:
  - SYS_ADMIN
  - SYS_RAWIO
  - SYS_MODULE
devices:
  - /dev/i2c-1:/dev/i2c-1:rw
options:
  mqtt_host: "core-mosquitto"
  mqtt_port: 1883
  mqtt_username: "mqtt"
  mqtt_password: "mqtt_password"
  pca_address: "0x40"
  pca9539_address: "0x74"
  pca9540_address: "0x70"
  i2c_bus: 1
  bme_interval: 30
  pca_frequency: 1000
  default_duty_cycle: 30
  pu_default_hz: 100.0
  mqtt_deep_clean: false
  led_indicator_interval: 30
  color_error: "red"
  color_ok: "green"
  color_diagnostic: "blue"
schema:
  mqtt_host: str
  mqtt_port: port
  mqtt_username: str?
  mqtt_password: password?
  mqtt_deep_clean: bool?
  pca_address: match(^0x[0-9A-Fa-f]{2}$)
  pca9539_address: match(^0x[0-9A-Fa-f]{2}$)?
  pca9540_address: match(^0x[0-9A-Fa-f]{2}$)?
  i2c_bus: int(0,10)?
  bme_interval: int(1,3600)?
  pca_frequency: int(24,1526)
  default_duty_cycle: int(0,100)
  pu_default_hz: float?
  led_indicator_interval: int(5,300)?
  color_error: list(red|green|blue|yellow|cyan|magenta|white|off)?
  color_ok: list(red|green|blue|yellow|cyan|magenta|white|off)?
  color_diagnostic: list(red|green|blue|yellow|cyan|magenta|white|off)?
